### PR TITLE
Merge progress bars for buildings and Bootstrap theme

### PR DESCRIPTION
**Pull request by olleharstedt**
Lots of work and testing still needs to be done, but if you agree with the changes, maybe we can merge them into a dev branch? And possible have an alpha version up and running to get feedback quickly. Good for motivating further development. :)

### CODE REVIEW

**Comment by Lukenickerson** [comment]
@olleharstedt 
Wow, that's a massive merge. It might take a while for me to go through all this. Do you have this running somewhere where I can try it out? 

Do you know how the licenses for jQuery, Bootstrap, and logger will interact with the license used for CivClicker? I know since it is "copyleft", rather than something like MIT, it's not something I'm familiar with.

**Comment by olleharstedt** [comment]
Hi!

Yes, it's running here: http://31.24.227.106/

But I've made more commits since this PR.

About license, no, don't know. :P Will have a look.

**Comment by olleharstedt** [comment]
There's also a reddit thread about this update here: https://www.reddit.com/r/incremental_games/comments/61s1go/civclicker_with_bootstrap_basic_theme_and/

The progress bars were not popular. :) But I will try to add them to upgrades instead/also, and see how it feels.

**Comment by Lukenickerson** [comment]
Sorry but I'm not really a fan of the addition of bootstrap. I guess I was rather attached to some of the style changes that I added. Is there any way you can separate the style changes from the code changes?

I think if the progress bars were a lot quicker than people might be okay with them -- more as an indication that the building action is happening, and less of a feeling of having to wait.

**Comment by olleharstedt** [comment]
OK. Nope, the HTML all uses the Bootstrap classes now. What I could do is to reapply your style using those classes, which would make the theme selector still possible. Don't know how much work that would be. :P 

They get quicker when population rises, since the time is divided by the square root of the population. But I might still add an option to just turn them off (or the other way, off by default).

**Comment by olleharstedt** [comment]
But I can try to make a new branch and cherry pick some stuff.

**Comment by olleharstedt** [comment]
I will close this for now, and maybe open another one with a more clearly defined boundary, without style changes.

**Pull request closed without merging**
